name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 1.8
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '8.0.345+1'
    - name: Build with Gradle
      run:
        ./gradlew build
    - name: Checkstyle & static check
      run: |
        ./gradlew --info checkstyle
        ./gradlew --info check
    - name: Spotbugs
      run: |
        ./gradlew spotbugsMain spotbugsTest
    - name: publish to Maven Central
      if: github.ref == 'refs/heads/master'
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
      run: |
        ./gradlew publish