name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8.0.345+1'
    - name: Build with Gradle
      run:
        ./gradlew build
    - name: Checkstyle & static check
      run: |
        ./gradlew --info checkstyle
        ./gradlew --info check
    - name: Spotbugs
      run: |
        ./gradlew spotbugsMain spotbugsTest
